### ISSUE TITLE
why use intanceId?

### ISSUE THREAD

**Issue by yafacex** [Pacific73/gorm-cache#2]
different process use diffrent instanceId, is it a waste of memory?

**Comment by Pacific73** [comment]
To be more accurate, the instance you created can be shared among different processes, since db instance itself can be accessed in different processes because the cache instance is attached to the db instance. The purpose of instance id is to handle the situation where you use 2 cache instances on 2 different db instances while only using 1 shared redis server for caching. in that case, keys would have conflicts if we don't add an instance id prefix before key names for isolating.
