### ISSUE TITLE
How to support Tenant?

### ISSUE THREAD

**Issue by rts-gordon** [Pacific73/gorm-cache#22]
Hi @Pacific73 
  Can gorm-chche support Tenant?  

  For example: there are many tenant in my system, they can access the same Table:task with different product Id. When Tenant A list task list A with product A Id, if Tenant B update his task B, this operation will not remove task list A in Cache. 

  In another word, A tenant Create/Update/Delete operations should only affect cached data associated with that tenant, can't affect other tenant cache data.

  Thank you.

**Comment by Pacific73** [comment]
If you mean multiple tenants in ONE SINGLE PROCESS, then the answer is WE CANNOT SUPPORT.

`In another word, A tenant Create/Update/Delete operations should only affect cached data associated with that tenant, can't affect other tenant cache data.`
↓
This is not a usual and correct way of dealing with data accessed by multiple clients. Why not operating them in memory rather than database?
